# Please fill these placeholders before running this application:
# 1. ${tenant-id}
# 2. ${resource-server-1-client-id}
# 3. ${resource-server-1-client-secret}
# 4. ${resource-server-2-client-id}

logging:
  level:
    root: DEBUG
server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        provider:
          azure-active-directory:
            issuer-uri: https://login.microsoftonline.com/${tenant-id}/v2.0 # Refs: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#webflux-oauth2-login-openid-provider-configuration
        registration:
          resource-server-1-resource-server-2:
            provider: azure-active-directory
            client-id: ${resource-server-1-client-id}
            client-secret: ${resource-server-1-client-secret}
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
            scope: api://${resource-server-2-client-id}/resource-server-2.scope-1
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/${tenant-id}/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/${tenant-id}/v2.0
          audience: ${resource-server-1-client-id}
