spring:
  thymeleaf:
    cache: false
  cloud:
    azure:
      appconfiguration:
        watch:
          enabled: True
          delay: 5s
config:
  message: Hi
feature-management:
  feature-flags:
    -
      id: beta
      enabled: true
    -
      id: dark-theme
      enabled: true
      conditions:
        client-filters:
          -
            name: Random
            parameters:
              chance: "50"
    -
      id: beta-ab
      enabled: true
      conditions:
        client-filters:
          -
            name: Random
            parameters:
              chance: "50"
          -
            name: ClientFilter
            parameters:
              clientIp: 10.0.0.1 