spring:
  thymeleaf:
    cache: false
  config:
    import: azureAppConfiguration
  cloud:
    azure:
      appconfiguration:
        stores:
          - 
            endpoint: ${CONFIGSTORE_ENDPOINT}
            feature-flags:
              enabled: true
            monitoring:
              enabled: true
              triggers:
                -
                  key: sentinel
