# If we configure the spring.cloud.azure.active-directory.client-id or spring.cloud.azure.active-directory.app-id-uri will be to check the audience.
# In v2.0 tokens, this is always the client ID of the API, while in v1.0 tokens it can be the client ID or the resource URI used in the request.
# If you are using v1.0 tokens, configure both to properly complete the audience validation.

server:
  port: 8082

spring:
  cloud:
    azure:
      active-directory:
        tenant-id: ${your-tenant-id}
#       client-id:  ${your-client-id}
#       app-id-uri:  ${your-app-id-uri}

