feature_management:
  feature_flags:
    - id: Beta
      enabled: true
      conditions:
        client-filters:
          - name: Microsoft.Targeting
            parameters:
              Audience:
                Users:
                  - Jeff
                  - Alicia
                Groups:
                  - Name: Ring0
                    RolloutPercentage: 100
                  - Name: Ring1
                    RolloutPercentage: 100
                DefaultRolloutPercentage: 50
                Exclusion:
                  Users:
                    - Ross
                  Groups:
                    - Ring2